const $ = id => document.getElementById(id);
const API = window.NIMBUS_API_BASE || '';
let token = localStorage.getItem('nimbus_v27_token') || '';
function log(msg,obj){ $('logBox').textContent = `[${new Date().toLocaleTimeString()}] ${msg}\n` + (obj?JSON.stringify(obj,null,2)+'\n':'') + $('logBox').textContent; }
async function api(path, opts={}){ const headers={'content-type':'application/json'}; if(token) headers.authorization='Bearer '+token; const res=await fetch(API+path,{...opts,headers:{...headers,...(opts.headers||{})}}); const data=await res.json().catch(()=>({ok:false,error:'bad_json'})); if(['expired_token','invalid_token','missing_token'].includes(data.error)){ localStorage.removeItem('nimbus_v27_token'); token=''; renderAuth(); } return data; }
function renderAuth(){ const on=!!token; $('loginCard').classList.toggle('hidden',on); $('app').classList.toggle('hidden',!on); $('logoutBtn').classList.toggle('hidden',!on); if(on) refreshAll(); }
async function login(){ const pin=$('pinInput').value.trim(); const data=await api('/api/login',{method:'POST',body:JSON.stringify({pin})}); if(data.ok){ token=data.token; localStorage.setItem('nimbus_v27_token',token); $('loginMsg').textContent=''; renderAuth(); } else $('loginMsg').textContent=data.error||'Login failed'; }
async function refreshAll(){ const dash=await api('/api/dashboard'); const latest=await api('/api/latest?limit=80'); const manual=await api('/api/manual-sources?limit=80'); const queue=await api('/api/queue?limit=80'); renderStats(dash.counts||{}); renderLinks(latest.items||[]); renderManual(manual.items||[]); renderQueue(queue.items||[]); }
function renderStats(c){ $('stats').innerHTML = [['Links',c.mega_links||0],['Queue',c.pending_queue||0],['Checked',c.health_checked||0],['Likely Valid',c.likely_valid||0]].map(([k,v])=>`<div class="stat"><span>${k}</span><b>${v}</b></div>`).join(''); }
function renderLinks(items){ $('results').innerHTML = items.length ? items.map(x=>`<div class="item"><a href="${esc(x.mega_url)}" target="_blank" rel="noopener">${esc(x.mega_url)}</a><p><span class="badge">${esc(x.link_type||'')}</span><span class="badge ${esc(x.health_status||'unchecked')}">${esc(x.health_status||'unchecked')}</span><span class="badge">confidence ${esc(x.confidence||'')}</span><br>${esc(x.title||'')}<br><span>${esc(x.source_domain||'')} · ${esc(x.health_reason||'')}</span></p><button data-url="${esc(x.mega_url)}" class="copy">Copy</button></div>`).join('') : '<p class="muted">No links yet.</p>'; document.querySelectorAll('.copy').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.url)); }
function renderManual(items){ $('manualSources').innerHTML = items.length ? items.map(x=>`<div class="item"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a><p><span>${esc(x.reason||'manual_review')} · ${esc(x.domain||'')}</span></p></div>`).join('') : '<p class="muted">No manual review sources.</p>'; }
function renderQueue(items){ $('queueBox').innerHTML = items.length ? items.map(x=>`<div class="item"><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.url)}</a><p><span>${esc(x.status)} · priority ${esc(x.priority)} · attempts ${esc(x.attempts)}</span></p></div>`).join('') : '<p class="muted">Queue is empty.</p>'; }
async function runSearch(mode, extra={}){ log('Running '+mode); const data=await api('/api/search',{method:'POST',body:JSON.stringify({mode,...extra})}); log('Finished '+mode,data.summary||data); await refreshAll(); }
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
$('loginBtn').onclick=login; $('pinInput').onkeydown=e=>{if(e.key==='Enter')login()}; $('logoutBtn').onclick=()=>{localStorage.removeItem('nimbus_v27_token');token='';renderAuth()}; $('manualBtn').onclick=()=>runSearch('manual',{query:$('query').value,limit:16}); $('autoBtn').onclick=()=>runSearch('auto',{reset:true,limit:16}); $('continueBtn').onclick=()=>runSearch('auto',{continueScan:true,limit:16}); $('scanUrlBtn').onclick=()=>runSearch('extract-url',{url:$('urlInput').value}); $('schemaBtn').onclick=async()=>{const d=await api('/api/schema');log('DB schema checked',d);refreshAll()}; $('processQueueBtn').onclick=async()=>{const d=await api('/api/process-queue',{method:'POST',body:JSON.stringify({limit:20})});log('Queue processed',d);refreshAll()}; $('checkBtn').onclick=async()=>{const d=await api('/api/check-links',{method:'POST',body:JSON.stringify({limit:30})});log('Health check done',d);refreshAll()}; $('dashboardBtn').onclick=async()=>{const d=await api('/api/dashboard');log('Dashboard',d);renderStats(d.counts||{})}; $('refreshBtn').onclick=refreshAll; $('exportBtn').onclick=()=>{location.href='/api/export?format=csv'}; renderAuth();
