const $=s=>document.querySelector(s);
let token=localStorage.getItem('nimbus_admin_token')||'';
let sourcePage=1,sourcePages=1;
const headers=()=>({'content-type':'application/json',...(token?{'x-nimbus-token':token}:{})});
const api=async(path,opts={})=>{const r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});const j=await r.json().catch(()=>({ok:false,error:`http_${r.status}`}));if(!r.ok)throw new Error(j.error||`http_${r.status}`);return j};
for(const b of document.querySelectorAll('nav button'))b.onclick=()=>{document.querySelectorAll('nav button,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.page).classList.add('active')};
const metric=(v,l)=>`<div class="metric"><strong>${v??0}</strong><span>${l}</span></div>`;
async function refresh(){try{const d=await api('/api/stats');$('#stats').innerHTML=metric(d.sources.enabled,'SOURCES ON')+metric(d.sources.disabled,'SOURCES OFF')+metric(d.runs,'RUNS')+metric(d.links,'LINKS')+metric(d.tasks?.pending||0,'PENDING')+metric(d.tasks?.queued||0,'QUEUED')+metric(d.tasks?.done||0,'DONE')+metric(d.tasks?.failed||0,'FAILED');const r=d.active;$('#run').innerHTML=r?`<p><b>Run ${r.id}</b></p><div class="progress"><span style="width:${Math.max(0,Math.min(100,r.progress||0))}%"></span></div><p>${Number(r.progress||0).toFixed(2)}% · ${Number(r.completed_tasks||0)+Number(r.failed_tasks||0)}/${r.total_tasks} · ${r.status}</p>`:'<p>No run yet.</p>';$('#dashboardLog').textContent=JSON.stringify({ok:true,version:d.version},null,2)}catch(e){$('#dashboardLog').textContent=JSON.stringify({ok:false,error:e.message},null,2)}}
$('#refresh').onclick=refresh;
for(const [id,path] of [['resume','/api/run/resume'],['pause','/api/run/pause'],['cancelRun','/api/run/cancel']])$('#'+id).onclick=async()=>{try{$('#dashboardLog').textContent=JSON.stringify(await api(path,{method:'POST'}),null,2);await refresh()}catch(e){$('#dashboardLog').textContent=e.message}};
$('#startAuto').onclick=async()=>{try{$('#autoLog').textContent=JSON.stringify(await api('/api/run/start',{method:'POST',body:JSON.stringify({mode:'autoscan'})}),null,2);await refresh()}catch(e){$('#autoLog').textContent=e.message}};
$('#startSearch').onclick=async()=>{try{$('#searchLog').textContent=JSON.stringify(await api('/api/run/start',{method:'POST',body:JSON.stringify({mode:'search',keyword:$('#keyword').value})}),null,2);await refresh()}catch(e){$('#searchLog').textContent=e.message}};
$('#extractBtn').onclick=async()=>{try{const d=await api('/api/extract',{method:'POST',body:JSON.stringify({text:$('#extractText').value})});$('#extractLog').textContent=d.links.join('\n\n')||'No valid folders found.'}catch(e){$('#extractLog').textContent=e.message}};
async function archive(){try{const d=await api('/api/archive');$('#archiveList').innerHTML=d.results.length?d.results.map(r=>`<div class="result"><a href="${r.link}" target="_blank" rel="noopener">${r.link}</a><div class="muted">${r.health} · score ${r.score} · ${r.source_id}</div></div>`).join(''):'<p>No archive results.</p>'}catch(e){$('#archiveList').textContent=e.message}}$('#reloadArchive').onclick=archive;
async function sources(){try{const search=encodeURIComponent($('#sourceSearch').value||'');const d=await api(`/api/sources?page=${sourcePage}&limit=50&search=${search}`);sourcePages=d.pages;$('#sourceSummary').innerHTML=`<p>${d.total} matching · page ${d.page}/${d.pages}</p>`;$('#sourcePage').textContent=`${d.page} / ${d.pages}`;$('#sourceList').innerHTML=d.sources.map(s=>`<div class="source"><label><input type="checkbox" data-source="${s.id}" ${s.enabled?'checked':''}> <b>${s.name}</b></label><div class="muted">${s.category} · priority ${s.priority} · yield ${s.yield_per_100||0}/100 · failures ${s.failures||0} · blocked ${s.blocked||0}</div></div>`).join('');for(const c of document.querySelectorAll('[data-source]'))c.onchange=async()=>{try{await api('/api/sources/toggle',{method:'POST',body:JSON.stringify({id:c.dataset.source,enabled:c.checked})})}catch(e){c.checked=!c.checked;alert(e.message)}}}catch(e){$('#sourceSummary').textContent=e.message}}
$('#reloadSources').onclick=()=>{sourcePage=1;sources()};$('#sourceSearch').onchange=()=>{sourcePage=1;sources()};$('#prevSources').onclick=()=>{if(sourcePage>1){sourcePage--;sources()}};$('#nextSources').onclick=()=>{if(sourcePage<sourcePages){sourcePage++;sources()}};$('#resetSources').onclick=async()=>{try{await api('/api/sources/reset',{method:'POST'});sourcePage=1;await sources()}catch(e){$('#sourceSummary').textContent=e.message}};
$('#adminToken').value=token;$('#saveToken').onclick=()=>{token=$('#adminToken').value.trim();localStorage.setItem('nimbus_admin_token',token);$('#toolsLog').textContent='Token saved locally.'};
$('#repair').onclick=async()=>{try{$('#toolsLog').textContent='Repairing...';$('#toolsLog').textContent=JSON.stringify(await api('/api/db/repair',{method:'POST'}),null,2);await refresh()}catch(e){$('#toolsLog').textContent=e.message}};
$('#diagnostics').onclick=async()=>{try{$('#toolsLog').textContent=JSON.stringify(await api('/api/diagnostics'),null,2)}catch(e){$('#toolsLog').textContent=e.message}};
refresh();setInterval(refresh,10000);
