CREATE TABLE IF NOT EXISTS mega_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mega_url TEXT UNIQUE NOT NULL,
  source_url TEXT,
  title TEXT,
  query TEXT,
  region TEXT,
  discovered_at TEXT DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS protected_sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  source_url TEXT UNIQUE NOT NULL,
  title TEXT,
  reason TEXT,
  query TEXT,
  region TEXT,
  discovered_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS scan_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  query TEXT,
  regions TEXT,
  pages_scanned INTEGER DEFAULT 0,
  mega_found INTEGER DEFAULT 0,
  protected_found INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
