import fs from 'node:fs';
import assert from 'node:assert/strict';
const worker=fs.readFileSync('_worker.js','utf8');
const ui=fs.readFileSync('index.html','utf8');
const schema=fs.readFileSync('schema.sql','utf8');
const sw=fs.readFileSync('service-worker.js','utf8');
const queueCfg=fs.readFileSync('wrangler.queue.jsonc','utf8');
const checks=[];
function ok(name, cond){assert.ok(cond,name);checks.push(name)}
ok('V34.2 version', worker.includes("34.2-resilient-pipeline"));
ok('No global queue fallback', !worker.includes("processQueue(env, '', Math.min"));
ok('Pause checked server side', worker.includes("state.status==='paused'"));
ok('Source cursor does not wrap', !worker.includes("(sourceOffset + selected.length) % allSources.length"));
ok('Sources exhausted persisted', worker.includes('sources_exhausted'));
ok('Accurate enqueue changes', worker.includes('meta?.changes'));
ok('Cloud queue send enabled', worker.includes('qbind.send(it)'));
ok('Source fetch dedup', worker.includes("skipped:'recently_visited_source'"));
ok('Monotonic progress floor', worker.includes('progress_floor'));
ok('Health valid unified', worker.includes("health IN ('alive','valid')"));
ok('Separate progress bars', ui.includes('resultBar')&&ui.includes('scanBar'));
ok('UI stops on paused', ui.includes("status==='paused'"));
ok('UI uses server queue polling', ui.includes('serverQueue'));
ok('V34 service worker cache', sw.includes('v34'));
ok('Cron configured', queueCfg.includes('*/5 * * * *'));
ok('Canonical schema upgraded', schema.includes('sources_exhausted')&&schema.includes('cooldown_until'));

ok('queue worker can re-enqueue child tasks', queueCfg.includes('\"producers\"') && queueCfg.includes('\"binding\": \"QUEUE\"'));
ok('crawl children are sent to cloud queue', worker.includes('await enqueueManyCloud(env, childTasks)'));
ok('progress counts all nonterminal queue states', worker.includes("status IN ('pending','running','leased','retry_wait')"));
ok('frontend clears expired auth automatically', ui.includes("session_expired"));
ok('frontend protects against disappearing source catalog', ui.includes('empty_source_catalog'));
ok('Queue batch orchestrates next source slice', worker.includes('runIds.map(id=>orchestrateRun'));
ok('Resume drains orphaned D1 shadow tasks', worker.includes('Resume must make progress even when D1 contains orphaned shadow rows'));
ok('Normal source reads avoid 1000-row policy write', worker.includes('bulk_write:false') && !worker.match(/ensureSourcePolicy[\s\S]{0,1200}applySourcePreset\(env, 'high_yield'\)/));
ok('Free plan config has no custom limits', !queueCfg.includes('"limits"'));
ok('Conservative queue batch size', queueCfg.includes('"max_batch_size": 1') && queueCfg.includes('"max_concurrency": 1'));
console.log(JSON.stringify({ok:true,tests:checks.length,checks},null,2));
