import { uid, nowIso } from "../db/queries.js";
import { SYSTEM } from "../config.js";
import { processSourceDiscoveryTask } from "./discovery-runs.js";
import { recordQueueOperations, isQueueLimitError } from "../queue/usage.js";

export const SOURCE_QUEUE_SCHEMA="nimbus.source.queue.v1";
export const SOURCE_QUEUE_TYPE="source_discovery_batch";
export function makeSourceDiscoveryMessage({messageId,runId,tasks,enqueuedAt=nowIso()}){return{schema:SOURCE_QUEUE_SCHEMA,type:SOURCE_QUEUE_TYPE,message_id:messageId,run_id:runId,tasks:tasks.map(t=>({task_id:String(t.task_id),attempt:Number(t.attempt||0)})),enqueued_at:enqueuedAt};}
export function validateSourceDiscoveryMessage(body){if(!body||body.schema!==SOURCE_QUEUE_SCHEMA||body.type!==SOURCE_QUEUE_TYPE)return{ok:false};if(!body.message_id||!body.run_id||!Array.isArray(body.tasks)||!body.tasks.length)return{ok:false};return{ok:true,value:body};}
export async function dispatchSourceDiscovery(env,runId,limit=SYSTEM.sourceDiscoveryDispatchTasks){const run=await env.DB.prepare(`SELECT status FROM source_discovery_runs WHERE id=?`).bind(runId).first();if(!run||run.status!=="running")return{queued:0,skipped:"run_not_running"};const rows=await env.DB.prepare(`SELECT id,attempts FROM source_discovery_tasks WHERE run_id=? AND status IN ('pending','failed') ORDER BY priority DESC,created_at ASC LIMIT ?`).bind(runId,Math.max(1,Math.min(limit,SYSTEM.sourceDiscoveryDispatchTasks))).all();const tasks=rows.results||[];if(!tasks.length)return{queued:0,messages:0};const now=nowIso();const marked=await env.DB.batch(tasks.map(t=>env.DB.prepare(`UPDATE source_discovery_tasks SET status='dispatching',updated_at=? WHERE id=? AND run_id=? AND status IN ('pending','failed')`).bind(now,t.id,runId)));const selected=tasks.filter((_,i)=>marked[i]?.meta?.changes===1);const groups=[];for(let i=0;i<selected.length;i+=SYSTEM.sourceDiscoveryTasksPerMessage)groups.push(selected.slice(i,i+SYSTEM.sourceDiscoveryTasksPerMessage));const messages=groups.map(g=>makeSourceDiscoveryMessage({messageId:uid("smsg"),runId,tasks:g.map(t=>({task_id:t.id,attempt:t.attempts||0})),enqueuedAt:now}));try{await env.QUEUE.sendBatch(messages.map(body=>({body})));await recordQueueOperations(env.DB,{writes:messages.length}).catch(()=>{});await env.DB.batch(selected.map(t=>env.DB.prepare(`UPDATE source_discovery_tasks SET status='queued',message_id=?,queued_at=?,updated_at=? WHERE id=? AND status='dispatching'`).bind(messages[Math.floor(selected.indexOf(t)/SYSTEM.sourceDiscoveryTasksPerMessage)]?.message_id||null,now,now,t.id)));await env.DB.prepare(`UPDATE source_discovery_runs SET queue_messages=queue_messages+?,updated_at=? WHERE id=?`).bind(messages.length,now,runId).run();return{queued:selected.length,messages:messages.length};}catch(error){await env.DB.batch(selected.map(t=>env.DB.prepare(`UPDATE source_discovery_tasks SET status='pending',last_error=?,updated_at=? WHERE id=?`).bind(String(error?.message||error),nowIso(),t.id)));if(isQueueLimitError(error)){const fallback=await processSourceDiscoveryDirect(env,runId,{taskLimit:1,fetchBudget:SYSTEM.sourceDiscoveryDirectFetchBudget}).catch(e=>({processed:0,error:String(e)}));return{queued:0,queue_limit:true,fallback_automatic:true,fallback};}throw error;}}
export async function processSourceDiscoveryDirect(env,runId,{taskLimit=1,fetchBudget=16}={}){const rows=await env.DB.prepare(`SELECT id FROM source_discovery_tasks WHERE run_id=? AND status IN ('pending','failed') ORDER BY priority DESC,created_at ASC LIMIT ?`).bind(runId,taskLimit).all();let processed=0,used=0;for(const r of rows.results||[]){if(used>=fetchBudget)break;const out=await processSourceDiscoveryTask(env,r.id,{fetchBudget:fetchBudget-used});processed++;used+=Number(out.fetches||1);}return{processed,fetches:used,fetch_budget:fetchBudget};}
export async function consumeSourceDiscoveryMessage(env,body){const v=validateSourceDiscoveryMessage(body);if(!v.ok)return{ok:false,rejected:true};let retry=false;for(const item of v.value.tasks){const out=await processSourceDiscoveryTask(env,item.task_id);if(out.retry)retry=true;}await dispatchSourceDiscovery(env,v.value.run_id).catch(()=>{});return{ok:true,retry,runId:v.value.run_id};}
export async function recoverSourceDiscoveryRuntime(env,runId){const now=nowIso();await env.DB.prepare(`UPDATE source_discovery_tasks SET status='pending',lease_until=NULL,last_error='source_watchdog_recovered',updated_at=? WHERE run_id=? AND status IN ('dispatching','queued','running') AND (lease_until IS NULL OR lease_until<?)`).bind(now,runId,now).run();return dispatchSourceDiscovery(env,runId);}
