import { uid, nowIso } from "../db/queries.js";
import { fetchPage } from "../search/crawler.js";
import { extractMegaFolders } from "../extract/mega.js";
import { validateMegaFolderUrl } from "../results/mega-validation.js";
import { discoverCandidateUrls, registerSourceCandidates, promoteQualifiedCandidates } from "./discovery.js";
import { dispatchSourceDiscovery } from "./discovery-queue.js";
import { SYSTEM } from "../config.js";

const PROFILES=Object.freeze({quick:8,normal:20,deep:40,ultra:70});
const DDG_HTML="https://html.duckduckgo.com/html/?q=";
const DDG_LITE="https://lite.duckduckgo.com/lite/?q=";
const WAYBACK="https://web.archive.org/cdx/search/cdx?output=json&filter=statuscode:200&collapse=urlkey&fl=original&limit=50&url=";
function q(base,text){return`${base}${encodeURIComponent(text)}`;}
function folderParts(url){const m=String(url||"").match(/mega\.nz\/folder\/([A-Za-z0-9_-]+)(?:#([A-Za-z0-9_-]+))?/i);return{id:m?.[1]||"",key:m?.[2]||""};}
function variants(seed,round){const suffixes=["archive","mirror","collection","index","paste","forum","links","shared folder","recent","rss","sitemap","public list","directory","catalog"];const s=suffixes[round%suffixes.length];return[`${seed} ${s}`,`${seed} ${s} -site:mega.nz`,`${seed} ${round%2?"recent":"updated"}`];}
export function chunkItems(items,size=SYSTEM.sqlBatchSize){const out=[];for(let i=0;i<items.length;i+=Math.max(1,size))out.push(items.slice(i,i+Math.max(1,size)));return out;}
export function deriveDiscoveryOutcome({total=0,completed=0,failed=0,cancelled=0}={}){const done=completed+failed+cancelled;if(total<=0||done<total)return{status:"running",outcome:"pending"};if(failed===0)return{status:"completed",outcome:"success"};if(completed>0)return{status:"completed",outcome:"partial"};return{status:"failed",outcome:"failure"};}
function safeHost(value){try{return new URL(value).hostname;}catch{return null;}}

export async function buildDiscoverySeeds(db,{rounds=1,profile="normal"}={}){
  const limit=Math.min(100,PROFILES[profile]||PROFILES.normal);
  const links=await db.prepare(`SELECT l.normalized_url,l.source_id,s.template_url source_url FROM links l LEFT JOIN sources s ON s.id=l.source_id ORDER BY l.discovered_at DESC LIMIT ?`).bind(limit).all();
  const sources=await db.prepare(`SELECT id,template_url,name FROM sources ORDER BY rank_score DESC,priority DESC LIMIT ?`).bind(Math.min(30,limit)).all();
  const bases=[];
  for(const row of links.results||[]){const p=folderParts(row.normalized_url);if(!p.id)continue;const full=`"https://mega.nz/folder/${p.id}${p.key?`#${p.key}`:""}"`;const short=`"mega.nz/folder/${p.id}"`;bases.push({strategy:"link_reappearance",seed:p.id,fingerprint:p.id,originSourceId:row.source_id||null,originHost:safeHost(row.source_url),queries:[full,short,`"${p.id}" "mega.nz/folder"`,`"${encodeURIComponent(`https://mega.nz/folder/${p.id}`)}"`,`"https:\/\/mega.nz\/folder\/${p.id}"`]});}
  for(const row of sources.results||[]){try{const host=new URL(row.template_url).hostname;bases.push({strategy:"successful_source_expansion",seed:host,originSourceId:row.id,originHost:host,queries:[`"${host}" "mega.nz/folder"`,`related:${host} "mega.nz/folder"`,`site:${host} "mega.nz/folder"`]});}catch{}}
  for(const term of ["\"mega.nz/folder\" public index","\"mega.nz/folder\" archive","\"mega.nz/folder\" paste","\"mega.nz/folder\" collection","\"mega.nz/folder\" forum","\"mega.nz/folder\" mirror"])bases.push({strategy:"broad_discovery",seed:term,queries:[term]});
  const out=[],seen=new Set();
  for(let r=0;r<rounds;r++)for(const b of bases){for(const text of variants(b.queries[r%b.queries.length],r)){const provider=r%3===1?DDG_LITE:DDG_HTML;const url=q(provider,text);const key=`${b.strategy}|${url}`;if(!seen.has(key)){seen.add(key);out.push({...b,url,strategy:`${b.strategy}:${r%3===1?"ddg_lite":"ddg_html"}`,round:r+1,evidenceUrl:url});}}if(r%4===3&&b.seed&&/^[A-Za-z0-9_.-]+$/.test(b.seed)){const url=`${WAYBACK}${encodeURIComponent(`*.${b.seed}/*mega.nz/folder*`)}`;const key=`wayback|${url}`;if(!seen.has(key)){seen.add(key);out.push({...b,strategy:"wayback_backlink",url,round:r+1,evidenceUrl:url});}}}
  return out.slice(0,Math.max(1,limit*rounds));
}

export async function startSourceDiscovery(env,{rounds=1,profile="normal"}={}){
  const active=await env.DB.prepare(`SELECT id FROM source_discovery_runs WHERE status IN ('running','paused','recovering') LIMIT 1`).first();if(active)throw new Error(`active_source_discovery_run:${active.id}`);
  rounds=Math.max(1,Math.min(100,Number(rounds)||1));if(!PROFILES[profile])profile="normal";
  const seeds=await buildDiscoverySeeds(env.DB,{rounds,profile}),id=uid("srun"),now=nowIso();
  await env.DB.prepare(`INSERT INTO source_discovery_runs(id,status,profile,rounds,total_tasks,created_at,started_at,updated_at,outcome) VALUES(?,?,?,?,?,?,?,?,?)`).bind(id,"running",profile,rounds,seeds.length,now,now,now,"pending").run();
  for(const group of chunkItems(seeds,Math.min(SYSTEM.sqlBatchMax,SYSTEM.sqlBatchSize))){await env.DB.batch(group.map((s,i)=>env.DB.prepare(`INSERT INTO source_discovery_tasks(id,run_id,strategy,seed_value,url,status,priority,created_at,updated_at,origin_source_id,origin_host,input_fingerprint,evidence_url) VALUES(?,?,?,?,?,'pending',?,?,?,?,?,?,?)`).bind(uid("stask"),id,s.strategy,s.seed,s.url,100-(i%50),now,now,s.originSourceId||null,s.originHost||null,s.fingerprint||null,s.evidenceUrl||s.url)));}
  const dispatch=await dispatchSourceDiscovery(env,id);return{run_id:id,status:"running",profile,rounds,total_tasks:seeds.length,dispatch};
}
function rootCandidates(urls){const m=new Map();for(const value of urls){try{const u=new URL(value);u.hash="";const root=`${u.protocol}//${u.host}/`;if(!m.has(u.hostname))m.set(u.hostname,{root,examples:[]});m.get(u.hostname).examples.push(value);}catch{}}return[...m.values()];}
async function profileDomain(env,domain,{fetchBudget=12,validationBudget=4}={}){
  const endpoints=[domain.root,new URL("sitemap.xml",domain.root).toString(),new URL("rss",domain.root).toString(),new URL("feed",domain.root).toString(),new URL("archive",domain.root).toString(),new URL("recent",domain.root).toString()];
  let pages=0,ok=0,blocked=0,latency=0;const allLinks=new Map(),allCandidates=[];
  for(const url of endpoints){if(pages>=fetchBudget)break;const p=await fetchPage(url,{timeoutMs:6000});pages++;latency+=Number(p.latency||0);if(p.ok)ok++;if([401,403,429].includes(Number(p.status)))blocked++;for(const l of extractMegaFolders(p.text||""))allLinks.set(l.normalizedUrl,l);allCandidates.push(...discoverCandidateUrls(p.text||"",p.finalUrl||url,{limit:40}));}
  let alive=0,dead=0,unknown=0;for(const link of [...allLinks.values()].slice(0,validationBudget)){const v=await validateMegaFolderUrl(link.normalizedUrl,{timeoutMs:5000});if(v.status==="alive")alive++;else if(v.status==="dead"||v.status==="invalid")dead++;else unknown++;}
  unknown+=Math.max(0,allLinks.size-(alive+dead+unknown));
  return{pages,ok,blocked,latency:pages?latency/pages:0,mega:[...allLinks.values()],candidates:[...new Set(allCandidates)],alive,dead,unknown};
}
async function syncSourceDiscoveryProgress(db,runId){const c=await db.prepare(`SELECT COUNT(*) total,SUM(status='completed') completed,SUM(status IN ('failed','dead')) failed,SUM(status='cancelled') cancelled FROM source_discovery_tasks WHERE run_id=?`).bind(runId).first();const total=Number(c?.total||0),completed=Number(c?.completed||0),failed=Number(c?.failed||0),cancelled=Number(c?.cancelled||0),done=completed+failed+cancelled;const {status,outcome}=deriveDiscoveryOutcome({total,completed,failed,cancelled});const progress=total?Math.min(100,done*100/total):100;await db.prepare(`UPDATE source_discovery_runs SET status=?,outcome=?,completed_tasks=?,failed_tasks=?,progress=?,completed_at=CASE WHEN ? IN ('completed','failed') THEN ? ELSE completed_at END,updated_at=? WHERE id=?`).bind(status,outcome,completed,failed,progress,status,nowIso(),nowIso(),runId).run();return{status,outcome,progress,total,completed,failed};}

export async function processSourceDiscoveryTask(env,taskId,{fetchBudget=SYSTEM.sourceDiscoveryFetchBudget}={}){
  const task=await env.DB.prepare(`SELECT t.*,r.status run_status FROM source_discovery_tasks t JOIN source_discovery_runs r ON r.id=t.run_id WHERE t.id=?`).bind(taskId).first();if(!task)return{retry:false,skipped:"missing"};
  if(task.run_status!=="running"){if(["queued","dispatching","running","failed"].includes(task.status))await env.DB.prepare(`UPDATE source_discovery_tasks SET status='pending',lease_until=NULL,updated_at=? WHERE id=?`).bind(nowIso(),taskId).run();return{retry:false,skipped:"run_not_running"};}
  const lease=new Date(Date.now()+SYSTEM.sourceDiscoveryLeaseSeconds*1000).toISOString();const got=await env.DB.prepare(`UPDATE source_discovery_tasks SET status='running',attempts=attempts+1,started_at=COALESCE(started_at,?),lease_until=?,updated_at=? WHERE id=? AND status IN ('pending','failed','queued','dispatching')`).bind(nowIso(),lease,nowIso(),taskId).run();if((got.meta?.changes||0)!==1)return{retry:false,skipped:"lease_not_acquired"};
  let fetches=0;
  try{
    const page=await fetchPage(task.url,{timeoutMs:7000});fetches++;const urls=discoverCandidateUrls(page.text||"",page.finalUrl||task.url,{limit:80});const domains=rootCandidates(urls);let discovered=domains.length,candidates=0,tested=0,promoted=0,novel=0,dupes=0,alive=0,dead=0,unknown=0;
    for(const d of domains.slice(0,Math.max(1,Math.min(8,fetchBudget-fetches)))){const prof=await profileDomain(env,d,{fetchBudget:Math.max(1,Math.min(6,fetchBudget-fetches))});fetches+=prof.pages;tested+=prof.pages;alive+=prof.alive;dead+=prof.dead;unknown+=prof.unknown;const fps=new Set(prof.mega.map(x=>folderParts(x.normalizedUrl).id).filter(Boolean));if(task.input_fingerprint)fps.add(task.input_fingerprint);let domainNovel=0,domainDup=0;for(const l of prof.mega){const exists=await env.DB.prepare(`SELECT 1 FROM links WHERE normalized_url=? LIMIT 1`).bind(l.normalizedUrl).first();if(exists)domainDup++;else domainNovel++;}novel+=domainNovel;dupes+=domainDup;
      const reg=await registerSourceCandidates(env.DB,{urls:[d.root,...d.examples.slice(0,3),...prof.candidates.slice(0,10)],sourceId:task.origin_source_id,sourceHost:task.origin_host,runId:task.run_id,megaLinksFound:prof.mega.length,novelLinksFound:domainNovel,aliveLinksFound:prof.alive,deadLinksFound:prof.dead,unknownLinksFound:prof.unknown,duplicateLinksFound:domainDup,successful:prof.ok>0,blockedFetches:prof.blocked,pagesTested:prof.pages,latency:prof.latency,megaFingerprints:[...fps],evidenceUrl:d.examples[0]||task.evidence_url||task.url});candidates+=reg.registered;if(fetches>=fetchBudget)break;}
    const p=await promoteQualifiedCandidates(env.DB,{limit:5});promoted+=p.promoted;await env.DB.prepare(`UPDATE source_discovery_tasks SET status='completed',completed_at=?,lease_until=NULL,result_json=?,last_error=NULL,updated_at=? WHERE id=?`).bind(nowIso(),JSON.stringify({domains:discovered,candidates,tested,promoted,novel,duplicates:dupes,alive,dead,unknown,fetches}),nowIso(),taskId).run();await env.DB.prepare(`UPDATE source_discovery_runs SET domains_discovered=domains_discovered+?,candidates_created=candidates_created+?,sources_tested=sources_tested+?,promoted_sources=promoted_sources+?,current_strategy=?,updated_at=? WHERE id=?`).bind(discovered,candidates,tested,promoted,task.strategy,nowIso(),task.run_id).run();const progress=await syncSourceDiscoveryProgress(env.DB,task.run_id);return{retry:false,runId:task.run_id,fetches,...progress};
  }catch(error){const attempts=Number(task.attempts||0)+1,dead=attempts>=SYSTEM.sourceDiscoveryMaxAttempts;await env.DB.prepare(`UPDATE source_discovery_tasks SET status=?,lease_until=NULL,last_error=?,updated_at=? WHERE id=?`).bind(dead?"dead":"failed",String(error?.message||error),nowIso(),taskId).run();const progress=await syncSourceDiscoveryProgress(env.DB,task.run_id);return{retry:!dead,runId:task.run_id,fetches,...progress,error:String(error?.message||error)};}
}
export async function processSourceDiscoveryStep(env,runId){return dispatchSourceDiscovery(env,runId);}
export async function sourceDiscoveryRun(db,id){const run=await db.prepare(`SELECT * FROM source_discovery_runs WHERE id=?`).bind(id).first();if(!run)return null;const states=await db.prepare(`SELECT status,COUNT(*) count FROM source_discovery_tasks WHERE run_id=? GROUP BY status`).bind(id).all();return{...run,task_counts:Object.fromEntries((states.results||[]).map(r=>[r.status,Number(r.count)]))};}
export async function listSourceDiscoveryRuns(db,{limit=20}={}){const r=await db.prepare(`SELECT * FROM source_discovery_runs ORDER BY created_at DESC LIMIT ?`).bind(limit).all();return{runs:r.results||[]};}
export async function sourceDiscoveryAction(db,id,action){const map={pause:"paused",resume:"running",cancel:"cancelled",recover:"recovering"};const next=map[action];if(!next)throw new Error("invalid_action");await db.prepare(`UPDATE source_discovery_runs SET status=?,updated_at=? WHERE id=?`).bind(next,nowIso(),id).run();if(action==="cancel")await db.prepare(`UPDATE source_discovery_tasks SET status='cancelled',lease_until=NULL,updated_at=? WHERE run_id=? AND status NOT IN ('completed','dead','cancelled')`).bind(nowIso(),id).run();if(action==="recover"){await db.prepare(`UPDATE source_discovery_tasks SET status='pending',lease_until=NULL,updated_at=? WHERE run_id=? AND status IN ('running','queued','dispatching','failed')`).bind(nowIso(),id).run();await db.prepare(`UPDATE source_discovery_runs SET status='running',updated_at=? WHERE id=?`).bind(nowIso(),id).run();}return sourceDiscoveryRun(db,id);}
